---
default_stages: [pre-commit]
default_language_version:
  python: python3
minimum_prek_version: '0.2.0'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: Check YAML files are valid
      - id: end-of-file-fixer
        name: Fix missing newline at end of files
        exclude: ^cursor_.*\.md$
      - id: trailing-whitespace
        name: Remove trailing whitespace
        exclude: ^cursor_.*\.md$
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=500']
      - id: check-merge-conflict
        name: Check for merge conflict markers
      - id: check-toml
        name: Check TOML files are valid

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
      - id: ruff
        name: Run Ruff linter
        args: [--fix]
      - id: ruff-format
        name: Run Ruff formatter

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        name: Run mypy type checker
        additional_dependencies:
          - typer
          - types-setuptools
        args: [--ignore-missing-imports]
        files: ^src/.*\.py$
